window.TOURENINFO={
  "Gaisberg_Gipfel.gpx": {
    "Gaisberg_Gipfel.gpx/Titel": "Gaisberg_Gipfel",
    "Gaisberg_Gipfel.gpx/Kurztext": "Ambitionierte Biker mit entsprechender Kondition und Technik finden auf dieser rund 69 Kilometer langen Mountainbike-Rundtour ihre sportliche Herausforderung. Die anspruchsvollen Streckenabschnitte %uFFFD es werden rund 1.750 H%uFFFDhenmeter %uFFFDberwunden %uFFFD werden mit einem genussvollen Erlebnis belohnt. Beim Singletrail Plumsjoch ist K%uFFFDnnen und h%uFFFDchste Konzentration angesagt. Kurz vor dem Ende ist eine Abk%uFFFDhlung im Achensee vor allem in den Sommermonaten zu empfehlen.",
    "Gaisberg_Gipfel.gpx/ArtderTour": "Rundtour",
    "Gaisberg_Gipfel.gpx/Tourenbeschreibung": "Vom Bahnhof in Scharnitz geht es in s%uFFFDdlicher Richtung etwa 500 Meter zur Kirche. Hier zweigt eine Stra%uFFFDe links Richtung %uFFFDGaisberg_Gipfelt%uFFFDler%uFFFD ab. Vorbei am gro%uFFFDen Parkplatz f%uFFFDhrt man bis zur Abzweigung zum Gaisberg_Gipfelhaus. Nun f%uFFFDhrt die Strecke (Radroute Nr. 595) links ansteigend ins Gaisberg_Gipfeltal hinein. Man bleibt bis zum Gaisberg_Gipfelhaus auf der gut ausgebauten Forststra%uFFFDe. Danach ist es nur mehr ein kurzer Anstieg bis zum Hochalmsattel. Nun folgt eine Abfahrt (etwas schlechterer Forstweg) bis hinunter zum Kleinen Ahornboden. Hier f%uFFFDhrt man auf einer guten Forststra%uFFFDe durch das Johannistal (einige kurze Bergaufpassagen) Richtung Hinterriss. Kurz vor dem Ende des Tales radelt man in zwei Serpentinen eine kurze Strecke bergauf und gelangt bald zur Mautstra%uFFFDe im Risstal. Nun f%uFFFDhrt man auf der asphaltierten Stra%uFFFDe taleinw%uFFFDrts und leicht ansteigend, bis man linkerhand die Abzweigung zur Plumsjochh%uFFFDtte erreicht. Nun folgt ein Anstieg von sieben Kilometern bis zur Plumsjochh%uFFFDtte kurz unterhalb des Plumssattels. Die Route f%uFFFDhrt weiter %uFFFDber den Sattel und gleich danach auf einem sehr steilen Forstweg (Singletrail Plumsjoch) in einigen Serpentinen (weniger routinierte Biker sollten unbedingt schieben!) hinunter zur Gernalm. Nun folgt man der asphaltierten Stra%uFFFDe talausw%uFFFDrts bis Pertisau. Durch den Ort geht es geradeaus bis man das Ufer des Achensees erreicht. Direkt am See folgt man dem Radweg Richtung Maurach bis ans Ende des Sees. Hier radelt man geradeaus weiter entlang der Achenseebahn Richtung Maurach. Die Strecke f%uFFFDhrt durch Maurach weiter bis zur Kirche von Eben. Hier %uFFFDberquert man die Bahngleise und zweigt gleich danach rechts auf einen Forstweg ab. Darauf rollt man nun immer bergab bis nach Wiesing. Bei der Dorfkirche in Wiesing f%uFFFDhrt man kurz rechts auf der Stra%uFFFDe Richtung Jenbach, um nach etwa hundert Metern wieder links in den Radweg abzuzweigen. Die Route f%uFFFDhrt nun bald unter der Autobahn hindurch und man radelt bis zur Br%uFFFDcke %uFFFDber den Inn. Man folgt dem Innradweg Richtung Innsbruck. Kurz nach dem Sportplatz zweigt man halbrechts auf eine kurze Auffahrt, die zur Innbr%uFFFDcke und ins Zentrum von Jenbach f%uFFFDhrt. Man %uFFFDberquert Autobahn und Eisenbahn und f%uFFFDhrt bis zum Kreisverkehr bei der Tankstelle. Nun folgt man den Wegweisern zum Bahnhof und erreicht diesen nach wenigen hundert Metern. Mit dem Zug geht es %uFFFDber Innsbruck (hier muss man umsteigen) zur%uFFFDck nach Scharnitz. Die Fahrradmitnahme ist nur in den Regionalz%uFFFDgen problemlos m%uFFFDglich!",
    "Gaisberg_Gipfel.gpx/Koordinaten Start": "47.392285, 11.267306",
    "Gaisberg_Gipfel.gpx/Start": "Bahnhof in Scharnitz",
    "Gaisberg_Gipfel.gpx/Koordinaten Ziel": "47.392285, 11.267306",
    "Gaisberg_Gipfel.gpx/Ziel": "Bahnhof in Scharnitz",
    "Gaisberg_Gipfel.gpx/auf": 1750,
    "Gaisberg_Gipfel.gpx/ab": 2200,
    "Gaisberg_Gipfel.gpx/HoechsterPunkt": 1800,
    "Gaisberg_Gipfel.gpx/Schwierigkeit": "schwer",
    "Gaisberg_Gipfel.gpx/Laenge": 69,
    "Gaisberg_Gipfel.gpx/Zeit": 8,
    "Gaisberg_Gipfel.gpx/Parkplatz": "Bahnhof Scharnitz",
    "Gaisberg_Gipfel.gpx/Koordinaten Parkplatz": "47.392285, 11.267306",
    "Gaisberg_Gipfel.gpx/Gebirgszug": "Gaisberg_Gipfel",
    "Gaisberg_Gipfel.gpx/Quelle": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-Gaisberg_Gipfel",
    "Gaisberg_Gipfel.gpx/Einkehr": "Langlaufst%uFFFDberl, Pertisau",
    "Gaisberg_Gipfel.gpx/EinkehrKoordinaten": "47.439611, 11.686361",
    "Gaisberg_Gipfel.gpx/EinkehrHomepage": "http://www.hotelkarlwirt.at/das-hotel/langlaufstueberl/",
    "Gaisberg_Gipfel.gpx/Einkehr1": "Seealm",
    "Gaisberg_Gipfel.gpx/Einkehr1Koordinaten": "47.426412, 11.728365",
    "Gaisberg_Gipfel.gpx/Einkehr1Homepage": "https://www.achensee.com/adressen/seealm/",
    "Gaisberg_Gipfel.gpx/specials": "Airrofan Skyglider - Rofan Cable Car Company",
    "Gaisberg_Gipfel.gpx/specialsKoordinaten": "47.425424, 11.751229",
    "Gaisberg_Gipfel.gpx/specialsWebsite": "https://www.tripadvisor.at/Attraction_Review-g658716-d2357561-Reviews-Airrofan_Skyglider_Rofan_Cable_Car_Company-Maurach_Eben_am_Achensee_Tirol_Austria.html",
    "Gaisberg_Gipfel.gpx/specials1": "Strandbad Buchau",
    "Gaisberg_Gipfel.gpx/specials1Koordinaten": "47.430995, 11.734843",
    "Gaisberg_Gipfel.gpx/specials1Website": "https://www.achensee.com/badestrand_buchau_sommer/",
    "Gaisberg_Gipfel.gpx/wetterLink1": "http://www.wetter.at/wetter/oesterreich/tirol/seefeld-in-tirol/widget/w300/color-petrol?utm_source=widget&utm_medium=",
    "Gaisberg_Gipfel.gpx/wetterLink2": "http://www.wetter.at/wetter/oesterreich/tirol/seefeld-in-tirol",
    "Gaisberg_Gipfel.gpx/WetterOrt": "Seefeld in Tirol",
    "Gaisberg_Gipfel.gpx/Foto": "bilder/risstal-Gaisberg_Gipfel.jpg",
  },
  
    "Pillerseetal.gpx/Titel": "Pillerseetal",
    "Pillerseetal.gpx/Kurztext": "Diese gem%uFFFDtliche und 50 Kilometer lange Rundtour f%uFFFDhrt Sie auf sehr guten Radwegen und Nebenstra%uFFFDen zum Ziel. Die rund 900 H%uFFFDhenmeter sind leicht zu bew%uFFFDltigen, da sich die Anstiege gleichm%uFFFD%uFFFDig %uFFFDber die gesamte Strecke verteilen. Viele Gastst%uFFFDtten entlang der Strecke und die M%uFFFDglichkeit f%uFFFDr ein erfrischendes Bad im Pillersee machen diese Route zu einem entspannten und erholsamen Ausflug auf dem Mountainbike.",
    "Pillerseetal.gpx/ArtderTour": "Rundtour",
    "Pillerseetal.gpx/Tourenbeschreibung": "Vom Ortszentrum von Fieberbrunn f%uFFFDhrt man auf der Hauptstra%uFFFDe etwa 200 Meter in %uFFFDstlicher Richtung und zweigt links Richtung %uFFFDSch%uFFFDnau-Pertrach%uFFFD ab. Auf einer schmalen Asphaltstra%uFFFDe f%uFFFDhrt man etwa 60 H%uFFFDhenmeter hinauf in den Fieberbrunner Weiler Pertrach. Nun folgt man der Mountainbikeroute %uFFFD17 Buchensteinwandrunde%uFFFD bis M%uFFFDhlau. Bei Erreichen der Landesstra%uFFFDe f%uFFFDhrt man linkerhand nur etwa 100 Meter auf dieser in westlicher Richtung und zweigt gleich wieder rechts auf den Radweg %uFFFD18 Kalksteinrunde%uFFFD ab. Auf dieser Route, die immer etwas erh%uFFFDht %uFFFDber dem Tal entlang f%uFFFDhrt, bleibt man nun bis zum kleinen St. Johanner Weiler Reitham. Hier zweigt man rechts ab und f%uFFFDhrt auf Nebenstra%uFFFDen, n%uFFFDrdlich des kleinen Flugplatzes vorbei und weiter %uFFFDber Oberhofen, Niederhofen nach Moosen. Hier %uFFFDberquert man die Bundesstra%uFFFDe und f%uFFFDhrt am Radweg Richtung Kirchdorf, sp%uFFFDter entlang der Gro%uFFFDache Richtung Erpfendorf. Bei Kilometer 21,7 zweigt man rechts auf den Radweg nach Erpfendorf ab, unterquert die Bundesstra%uFFFDe und erreicht bald den Ortskern. Ab hier folgt man immer den Radwegweisern nach Waidring. Im Dorfzentrum zweigt man rechts auf die Stra%uFFFDe nach St. Ulrich am Pillersee ab. Nach zwei Kilometern geht es rechts %uFFFDber eine kleine Br%uFFFDcke auf dem Radweg weiter, ehe man wieder die Stra%uFFFDe %uFFFDberquert und auf einem Fahrweg zum Pillersee (Badem%uFFFDglichkeit) radelt. An den Radwegweisern orientiert man sich immer an %uFFFDSt. Ulrich%uFFFD und sp%uFFFDter %uFFFDHochfilzen%uFFFD. Man durchquert die Beckenlandschaft und in s%uFFFDd%uFFFDstlicher Richtung geht es auf einer asphaltierten Stra%uFFFDe Richtung Wiesensee. Nach ca. einem Kilometer zweigt man links ab und f%uFFFDhrt gleich wieder rechts parallel zur Stra%uFFFDe auf einem Forstweg vorbei am Wiesensee (Kneippanlage) in den Hochfilzener Weiler Warming. Hier zweigt man zwischen den Bauernh%uFFFDfen %uFFFDH%uFFFDrl%uFFFD und %uFFFDGlaagut%uFFFD rechts auf die Radroute 17 %uFFFDBuchensteinwandrunde%uFFFD ab und folgt dieser bis Fieberbrunn.",
    "Pillerseetal.gpx/Koordinaten Start": "47.476926, 12.544588",
    "Pillerseetal.gpx/Start": "Fieberbrunn",
    "Pillerseetal.gpx/Koordinaten Ziel": "47.476926, 12.544588",
    "Pillerseetal.gpx/Ziel": "Fieberbrunn",
    "Pillerseetal.gpx/auf": 900,
    "Pillerseetal.gpx/ab": 970,
    "Pillerseetal.gpx/HoechsterPunkt": 940,
    "Pillerseetal.gpx/Schwierigkeit": "mittelschwer",
    "Pillerseetal.gpx/Laenge": 53,
    "Pillerseetal.gpx/Zeit": 6,
    "Pillerseetal.gpx/Parkplatz": "Bahnhof Fieberbrunn",
    "Pillerseetal.gpx/Koordinaten Parkplatz": "47.491241, 12.528752",
    "Pillerseetal.gpx/Gebirgszug": "Loferer Steinberge",
    "Pillerseetal.gpx/Quelle": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-pillerseetal",
    "Pillerseetal.gpx/Einkehr": "Seerestaurant Blattl am Pillersee",
    "Pillerseetal.gpx/EinkehrKoordinaten": "47.539914, 12.567615",
    "Pillerseetal.gpx/EinkehrHomepage": "https://www.kitzbueheler-alpen.com/de/st-ulrich-am-pillersee/info/restaurant-pillersee-blattl.html",
    "Pillerseetal.gpx/Einkehr1": "Alte Schmiede Weinstube- Pizzeria",
    "Pillerseetal.gpx/Einkehr1Koordinaten": "47.584216, 12.570386",
    "Pillerseetal.gpx/Einkehr1Homepage": "http://www.pizzeria-waidring.at/",
    "Pillerseetal.gpx/specials": "Jakobskreuz Aussichtspalttform",
    "Pillerseetal.gpx/specialsKoordinaten": "47.500756, 12.571718",
    "Pillerseetal.gpx/specialsWebsite": "https://www.kitzbueheler-alpen.com/de/pillerseetal/sommer/jakobskreuz-buchensteinwand.html",
    "Pillerseetal.gpx/specials1": "Steinplatte Waidring Aussichtsplattform",
    "Pillerseetal.gpx/specials1Koordinaten": "47.587565, 12.565102",
    "Pillerseetal.gpx/specials1Website": "http://www.steinplatte.tirol/de/aussichtsplattform-1.html",
    "Pillerseetal.gpx/Foto": "bilder/waidrig_pillersee.jpg",
    "MariaWaldrast.gpx/Titel": "Maria Waldrast",
    "MariaWaldrast.gpx/Kurztext": "Mit dem Zug von Innsbruck nach Matrei und %uFFFDbers Stubeital zur%uFFFDck. Diese wundersch%uFFFDne Tour am Hang der Serles entlang l%uFFFDsst sich mit 4 Stunden Fahrtzeit an einem Nachmittag gem%uFFFDtlich einschieben und bietet f%uFFFDr den kurzen Zeitraum einige sch%uFFFDne Ausblicke. Der Mittlere Schwierigkeitsgrad sollte f%uFFFDr jeden der nicht das erste mal auf dem Bike sitzt schaffbar sein.",
    "MariaWaldrast.gpx/ArtderTour": "Rundtour",
    "MariaWaldrast.gpx/Tourenbeschreibung": "Ausgangspunkt ist der Bahnhof in Innsbruck. Mit dem Zug geht es zun%uFFFDchst nach Matrei am Brenner. Vom Bahnhof radelt man in n%uFFFDrdlicher Richtung durch das Ortszentrum bis zur Abzweigung %uFFFDM%uFFFDtzens, Wallfahrtskirche Maria Waldrast%uFFFD. Hier zweigt man links ab. Die Route f%uFFFDhrt zun%uFFFDchst unter der Autobahn hindurch zum Ortsteil M%uFFFDtzens. Nach den letzten H%uFFFDusern passiert man die Mautstelle und radelt zun%uFFFDchst entlang des Waldraster Baches. Die Strecke f%uFFFDhrt dann in einigen Serpentinen bis ins Almgel%uFFFDnde und weiter zum Wallfahrtskloster Maria Waldrast. Hier endet die asphaltierte Stra%uFFFDe und man f%uFFFDhrt geradeaus weiter auf einem Forstweg bis zum h%uFFFDchsten Punkt, der gleichzeitig den %uFFFDbergang ins Stubai darstellt. Hier gabelt sich die Forststra%uFFFDe und man nimmt die Abzweigung Richtung Mieders. Die Route (Nr. 559) f%uFFFDhrt nun immer abw%uFFFDrts bis zu den ersten H%uFFFDusern in Mieders. Bei der Talstation der Seilbahn f%uFFFDhrt man links auf der Stra%uFFFDe Richtung Fulpmes (%uFFFDKleine Talrunde 566%uFFFD). Nach 600 Metern zweigt man rechts ab. Immer geradeaus abw%uFFFDrts folgt man der Stra%uFFFDe, bald unter der Stubaitalstra%uFFFDe durch, bis zur Br%uFFFDcke %uFFFDber die Ruetz. Nach %uFFFDberqueren der Br%uFFFDcke radelt man rechts weiter talausw%uFFFDrts Richtung %uFFFDGallhof, Telfer Wiesen%uFFFD. Die Strecke steigt bald wieder an und der Forstweg gabelt sich bei Kilometer 18,7. Links aufw%uFFFDrts folgt man dem Weg %uFFFDTelfer Wiesen%uFFFD. Kurz nachdem man die Gleise der Stubaitalbahn %uFFFDberquert hat zweigt man spitzwinkelig rechts ab und radelt Richtung %uFFFDKreith, Mutters%uFFFD. Die Route f%uFFFDhrt nun in leichtem Auf und Ab durch Wiesen und W%uFFFDlder fast immer parallel zur Bahn bis zum Mutterer Ortsteil Kreith. Bei Erreichen der Asphaltstra%uFFFDe in Kreith folgt man dieser geradeaus bis zur Kirche von Mutters. Hier radelt man halbrechts abw%uFFFDrts Richtung Innsbruck, bis man kurz danach wieder die Bahngleise %uFFFDberquert. Sofort danach zweigt die Route Richtung Natters ab. Weiter geht es durch das Dorfzentrum und auf der Stra%uFFFDe Richtung Innsbruck. Bei einem Kreisverkehr erreicht man die Brennerbundesstra%uFFFDe und f%uFFFDhrt auf dieser einen guten Kilometer Richtung Innsbruck. Kurz vor dem Bahn%uFFFDbergang zweigt man rechts ab in eine Seitenstra%uFFFDe (Auto- und Motorradfahrverbot). Diese Stra%uFFFDe f%uFFFDhrt bis zur Bergiselsprungschanze (Zufahrtshinweise beachten!). Vom Sprungstadion radelt man weiter abw%uFFFDrts bis man wieder auf die Bundesstra%uFFFDe gelangt. Immer geradeaus f%uFFFDhrt die Route vorbei am Stift Wilten (rechterhand) und der Wiltener Basilika (linkerhand) ins Zentrum von Innsbruck. Entlang der Leopoldstra%uFFFDe f%uFFFDhrt man bis zur Triumphpforte. Hier zweigt man rechts in die Salurner Stra%uFFFDe ab und erreicht nach etwa 300 Metern den Innsbrucker Hauptbahnhof.",
    "MariaWaldrast.gpx/Koordinaten Start": "47.263363, 11.400469",
    "MariaWaldrast.gpx/Start": "Innsbruck Hauptbahnhof",
    "MariaWaldrast.gpx/Koordinaten Ziel": "47.263363, 11.400469",
    "MariaWaldrast.gpx/Ziel": "Innsbruck Hauptbahnhof",
    "MariaWaldrast.gpx/auf": 950,
    "MariaWaldrast.gpx/ab": 1350,
    "MariaWaldrast.gpx/HoechsterPunkt": 1690,
    "MariaWaldrast.gpx/Schwierigkeit": "mittelschwer",
    "MariaWaldrast.gpx/Laenge": 32,
    "MariaWaldrast.gpx/Zeit": 4,
    "MariaWaldrast.gpx/Parkplatz": "Innsbruck Hauptbahnhof",
    "MariaWaldrast.gpx/Koordinaten Parkplatz": "47.263363, 11.400469",
    "MariaWaldrast.gpx/Gebirgszug": "Tuxer Alpen",
    "MariaWaldrast.gpx/Quelle": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-maria-waldrast",
    "MariaWaldrast.gpx/Einkehr": "Maria Waldrastgasthof",
    "MariaWaldrast.gpx/EinkehrKoordinaten": "47.130788, 11.405729",
    "MariaWaldrast.gpx/EinkehrHomepage": "http://www.mariawaldrast.at/index.php/kloster-gasthof",
    "MariaWaldrast.gpx/Einkehr1": "Kirchbr%uFFFDcke Restaurant",
    "MariaWaldrast.gpx/Einkehr1Koordinaten": "47.162357, 11.366385",
    "MariaWaldrast.gpx/Einkehr1Homepage": "http://kirchbruecke.com/",
    "MariaWaldrast.gpx/specials": "Maria Waldrast Klosteranlage",
    "MariaWaldrast.gpx/specialsKoordinaten": "47.130788, 11.405729",
    "MariaWaldrast.gpx/specialsWebsite": "http://www.mariawaldrast.at/index.php/wallfahrtsort-maria-waldrast",
    "MariaWaldrast.gpx/specials1": "Pfarrkirche Mari%uFFFD Himmelfahrt",
    "MariaWaldrast.gpx/specials1Koordinaten": "47.136798, 11.453339",
    "MariaWaldrast.gpx/specials1Website": "http://www.tirol-infos.at/innsbruck/mariae-himmelfahrt-bei-pfons.html",
    "MariaWaldrast.gpx/Foto": "bilder/MariaWaldrast.jpg",
    "Kaiserwinkl.gpx/Titel": "Kaiserwinkl",
    "Kaiserwinkl.gpx/Kurztext": "Nahe der Grenze zu Bayern f%uFFFDhrt diese 40 Kilometer lange Mountainbike-Strecke anfangs durch ein gemischtes Wald- und Almengebiet. Gefolgt von B%uFFFDchen, W%uFFFDldern und Wiesen gelangen Sie %uFFFDber gut ausgebaute Forstwege, Radwanderwege und wenig befahrene Nebenstra%uFFFDen zur%uFFFDck zu Ihrem Ausgangspunkt in K%uFFFDssen.",
    "Kaiserwinkl.gpx/ArtderTour": "Rundtour",
    "Kaiserwinkl.gpx/Tourenbeschreibung": "Ausgangspunkt ist der Hauptplatz von K%uFFFDssen. Von hier aus geht es zun%uFFFDchst auf der Gemeindestra%uFFFDe in s%uFFFDd%uFFFDstlicher Richtung zur Kitzb%uFFFDheler Ache, vorbei am Outdoorcenter Le Pirat. Kurz danach wird der Fluss und die Stra%uFFFDe %uFFFDberquert. Es folgt ein kurzer Anstieg bis man wiederum die Stra%uFFFDe nach Kitzb%uFFFDhel erreicht und auf dieser bis zur Abzweigung %uFFFD248 Klausenberg-Eggenalm%uFFFD bleibt. Auf der Mountainbikeroute Nr. 248 folgt ein Anstieg bis auf etwas %uFFFDber 1.000m Seeh%uFFFDhe. Dabei radelt man immer in s%uFFFDdlicher Richtung %uFFFDber dem Tal entlang bis zur Forststra%uFFFDengabelung mit der Beschilderung %uFFFD249 Straubingerhaus- Eggenalm%uFFFD. Hier zweigt man rechts ab und es geht die n%uFFFDchsten 5 Kilometer abw%uFFFDrts Richtung Erpfendorf. Auf dem Radweg Nr. 17 radelt man nun immer entlang der Kitzb%uFFFDheler Ache. Dabei folgt man immer der Radwegbeschilderung %uFFFDSt. Johann%uFFFD bzw. %uFFFDKirchdorf%uFFFD bis zur Br%uFFFDcke %uFFFDber die Kitzb%uFFFDheler Ache in Kirchdorf. Nachdem man die Br%uFFFDcke %uFFFDberquert hat, f%uFFFDhrt man auf der Stra%uFFFDe durch das Dorf, vorbei an der Kirche und weiter nach Gasteig. Nun radelt man weiter auf der Stra%uFFFDe in n%uFFFDrdlicher Richtung (K%uFFFDssen, Walchsee, Schwendt). Die Route steigt ab hier nur mehr etwa einen Kilometer leicht an. Danach rollt man immer leicht abw%uFFFDrts, vorbei am Weiler Griesenau und weiter durch den Wald, ehe man kurz nach der Br%uFFFDcke %uFFFDber den Bach links in den Radweg %uFFFDSteinerweg%uFFFD abzweigt. Der Bach wird noch einmal %uFFFDberquert und auf dem geschotterten Radweg f%uFFFDhrt man weiter Richtung Schwendt. Nach einem knappen Kilometer erreicht man eine schmale asphaltierte Stra%uFFFDe. Hier bei einer kleinen gelben Kapelle folgt man nicht mehr der Radwegbeschilderung nach Schwendt, sondern bleibt immer auf dieser Stra%uFFFDe. In weiterer Folge h%uFFFDlt man sich an die Beschilderung %uFFFDK%uFFFDssen%uFFFD bzw. %uFFFDWalchsee%uFFFD. In Niederbichl zweigt man rechts Richtung K%uFFFDssen ab. Die Route verl%uFFFDuft nun teilweise im Wald, sp%uFFFDter durch den Golfplatz. Nach dem Golfplatz h%uFFFDlt man sich kurz links und zweigt gleich nachdem man den Bach %uFFFDberquert hat wieder rechts ab. Nach etwas mehr als einem Kilometer erreicht man die Br%uFFFDcke %uFFFDber die Kitzb%uFFFDheler Ache (hier hei%uFFFDt sie Gro%uFFFDache). Nun sind es nur mehr wenige hundert Meter zur%uFFFDck zum Ausgangspunkt im Zentrum von K%uFFFDssen.",
    "Kaiserwinkl.gpx/Koordinaten Start": "47.668861, 12.404069",
    "Kaiserwinkl.gpx/Start": "K%uFFFDssen",
    "Kaiserwinkl.gpx/Koordinaten Ziel": "47.668861, 12.404069",
    "Kaiserwinkl.gpx/Ziel": "K%uFFFDssen",
    "Kaiserwinkl.gpx/auf": 700,
    "Kaiserwinkl.gpx/ab": 700,
    "Kaiserwinkl.gpx/HoechsterPunkt": 1030,
    "Kaiserwinkl.gpx/Schwierigkeit": "leicht",
    "Kaiserwinkl.gpx/Laenge": 40,
    "Kaiserwinkl.gpx/Zeit": 5,
    "Kaiserwinkl.gpx/Parkplatz": "Hofer K%uFFFDssen",
    "Kaiserwinkl.gpx/Koordinaten Parkplatz": "47.663173, 12.396350",
    "Kaiserwinkl.gpx/Gebirgszug": "Kaisergebirge",
    "Kaiserwinkl.gpx/Quelle": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-kaiserwinkl",
    "Kaiserwinkl.gpx/Einkehr": "K%uFFFDserei in Kirchdorf",
    "Kaiserwinkl.gpx/EinkehrKoordinaten": "47.561463, 12.414330",
    "Kaiserwinkl.gpx/EinkehrHomepage": "http://www.wilder-kaeser.at/de/uralt-urgemuetlich.html",
    "Kaiserwinkl.gpx/Einkehr1": "Gasthaus Hohenkendl",
    "Kaiserwinkl.gpx/Einkehr1Koordinaten": "47.603940, 12.382375",
    "Kaiserwinkl.gpx/Einkehr1Homepage": "http://www.hohenkendl.com/de/",
    "Kaiserwinkl.gpx/specials": "Schauk%uFFFDserei",
    "Kaiserwinkl.gpx/specialsKoordinaten": "47.561463, 12.414330",
    "Kaiserwinkl.gpx/specialsWebsite": "http://www.wilder-kaeser.at/de/wir-freuen-uns-auf-sie.html",
    "Kaiserwinkl.gpx/specials1": "Museum Metzgerhaus",
    "Kaiserwinkl.gpx/specials1Koordinaten": "47.557505, 12.447250",
    "Kaiserwinkl.gpx/specials1Website": "https://www.kitzbueheler-alpen.com/de/kirchdorf/info/museum-im-metzgerhaus.html",
    "Kaiserwinkl.gpx/Foto": "bilder/walchensee-Kaiswinkl.jpg",
    "HoheSalve.gpx/Titel": "Hohe Salve",
    "HoheSalve.gpx/Kurztext": "Diese rund 36 Kilometer lange und mittelschwierige MTB-Tour bringt sie auf die Hohe Salve, ein Aussichtsberg mit 1.830 Metern H%uFFFDhe. Sehr gute Forststra%uFFFDen und asphaltierte Nebenstra%uFFFDen f%uFFFDhren auf dieser Strecke zu sch%uFFFDne Aussichtspunkte. Genie%uFFFDen Sie die herrliche Aussicht auf den Wilden Kaiser und lassen Sie Ihren Blick bis zu den Hohen Tauern schweifen. Rund 1.000 H%uFFFDhenmeter sind bei dieser Tour zu bew%uFFFDltigen %uFFFD ein Mindestma%uFFFD an Kondition ist Voraussetzung.",
    "HoheSalve.gpx/ArtderTour": "Rundtour",
    "HoheSalve.gpx/Tourenbeschreibung": "Ausgangspunkt ist der geb%uFFFDhrenfreie Parkplatz der Salvena Bergbahn in Hopfgarten. Vom Parkplatz geht es kurz zur Stra%uFFFDe hinunter, durch die Bahnunterf%uFFFDhrung und links weiter, etwa 500 Meter Richtung Kitzb%uFFFDhel. Nun zweigt man rechts zum Ortsteil Elsbethen ab. Man folgt dem Radweg durch das Siedlungsgebiet und kommt bald zur Abzweigung der Biketour Nr. 274 (Gruberberg). Hier beginnt der Anstieg auf der Asphaltstra%uFFFDe. Zuerst radelt man durch den Wald, sp%uFFFDter %uFFFDber Wiesen. Dabei folgt man immer den Radwegweisern (Nr. 274). Bei Kilometer 4,3 hat man den ersten Anstieg geschafft. Nun folgt man der Stra%uFFFDe abw%uFFFDrts (%uFFFDWestendorf, Lendwirt%uFFFD) bis zur Br%uFFFDcke %uFFFDber den Bach des Windautals. Man %uFFFDberquert den Bach und f%uFFFDhrt kurz talausw%uFFFDrts. Vor dem Lendwirt zweigt die Route rechts Richtung Westendorf ab. Nach einem kurzen Anstieg von knapp 100 H%uFFFDhenmetern erreicht man die Wiesen und Felder vor Westendorf. Nun geht es immer geradeaus zum Dorfzentrum. Bei der Tankstelle zweigt man halbrechts auf den Radweg Richtung Brixen/Kirchberg ab. Nun bleibt man bis Brixen auf dem Radweg. Bei der gro%uFFFDen Tafel %uFFFDBike Trail Brixental%uFFFD zweigt man links Richtung Ortskern ab. Es geht erst unter der Eisenbahn hindurch und weiter bis man die Dorfstra%uFFFDe in Brixen erreicht. Nun zweigt man links auf diese Stra%uFFFDe ab und radelt darauf, bis kurz nach dem Hotel %uFFFDResidenz Hubertus%uFFFD der Radweg Nr. 265 nach Hochbrixen- Hochs%uFFFDll abzweigt. Auf der Bikeroute Nr. 265 f%uFFFDhrt man zun%uFFFDchst noch auf einer Asphaltstra%uFFFDe, sp%uFFFDter auf einem Forstweg hinauf bis ins Schigebiet. Alternativ: Hier besteht auch die M%uFFFDglichkeit, sich mit der Gondelbahn nach Hochbrixen bringen zu lassen. 500 H%uFFFDhenmeter werden hier mit der Bahn zur%uFFFDckgelegt. Ab der Bergstation der Gondelbahn wird der Weg wieder flacher und man f%uFFFDhrt immer leicht auf und ab hin%uFFFDber nach Hochs%uFFFDll. Auf der asphaltierten Zufahrtsstra%uFFFDe radelt man nun in einigen Serpentinen hinunter nach S%uFFFDll. Der Radweg f%uFFFDhrt unter der Bundesstra%uFFFDe hindurch ins Dorfzentrum. Nun folgt man den gr%uFFFDnen Radwegweisern Richtung W%uFFFDrgl bis zur Talstation der Salvistabahn in Schwend bei Itter. Kurz nach dem Betriebsgeb%uFFFDude zweigt man links aufw%uFFFDrts Richtung Itter ab. Diese Stra%uFFFDe f%uFFFDhrt bis ins Ortszentrum von Itter. Von der Kirche geht es weiter Richtung Hopfgarten, ehe man in einer leichten Rechtskurve geradeaus in eine Nebenstra%uFFFDe zum Fu%uFFFDballplatz (%uFFFDEd%uFFFD) f%uFFFDhrt. Nach dem Fu%uFFFDballplatz radelt man links (Bikeroute Nr. 269) weiter durch die Felder. Der Weg steigt noch einmal leicht an und durch ein kurzes Waldst%uFFFDck gelangt man in den Weiler Hacha. Nun folgt man der Asphaltstra%uFFFDe hinunter zum Ausgangsort Hopfgarten. Man f%uFFFDhrt dabei immer Richtung Kirche und danach durch die Schmalzgasse, vorbei an der Touristinfo zum Salvena Parkplatz.",
    "HoheSalve.gpx/Koordinaten Start": "47.446109, 12.162167",
    "HoheSalve.gpx/Start": "Hopfgarten, Salvenaland",
    "HoheSalve.gpx/Koordinaten Ziel": "47.446109, 12.162167",
    "HoheSalve.gpx/Ziel": "Hopfgarten, Salvenaland",
    "HoheSalve.gpx/auf": 1100,
    "HoheSalve.gpx/ab": 1100,
    "HoheSalve.gpx/HoechsterPunkt": 1290,
    "HoheSalve.gpx/Schwierigkeit": "mittelschwer",
    "HoheSalve.gpx/Laenge": "36,5",
    "HoheSalve.gpx/Zeit": 5,
    "HoheSalve.gpx/Parkplatz": "Parkplatz bei der Talstation der Salvenabahn in Hopfgarten",
    "HoheSalve.gpx/Koordinaten Parkplatz": "47.446109, 12.162167",
    "HoheSalve.gpx/Gebirgszug": "Kitzb%uFFFDheler Alpen",
    "HoheSalve.gpx/Quelle": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-hohe-salve",
    "HoheSalve.gpx/Einkehr": "Filzalm",
    "HoheSalve.gpx/EinkehrKoordinaten": "47.463504, 12.220496",
    "HoheSalve.gpx/EinkehrHomepage": "https://www.kitzbueheler-alpen.com/de/brixen-im-thale/info/filzalm.html",
    "HoheSalve.gpx/Einkehr1": "Hexenalm",
    "HoheSalve.gpx/Einkehr1Koordinaten": "47.497888, 12.197728",
    "HoheSalve.gpx/Einkehr1Homepage": "http://www.hexenalm-soell.at/",
    "HoheSalve.gpx/specials": "Baden Filzalmsee",
    "HoheSalve.gpx/specialsKoordinaten": "47.462960, 12.224004",
    "HoheSalve.gpx/specialsWebsite": "http://www.filzalmsee.at/de/",
    "HoheSalve.gpx/specials1": "Hexenwasser",
    "HoheSalve.gpx/specials1Koordinaten": "47.480283, 12.197561",
    "HoheSalve.gpx/specials1Website": "http://www.hexenwasser.at/de/homepage/",
    "HoheSalve.gpx/Foto": "bilder/wilder-kaiser-Brixental-Hohe salve.jpg",
    "Marienbergjoch.gpx/Titel": "Marienbergjoch",
    "Marienbergjoch.gpx/Kurztext": "Diese Route ist f%uFFFDr anspruchsvolle Mountainbiker genau das Richtige. Die fordernde Route mit rund 1.200 H%uFFFDhenmeter belohnt mit einem wunderbaren Ausblick auf das Zugspitzmassiv im Norden und auf die %uFFFDtztaler und Stubaier Alpen im S%uFFFDden. Ein Sprung in den sch%uFFFDnen Weisensee, in den malerischen Blindsee oder den beliebten Mittersee sorgen f%uFFFDr eine willkommene Erfrischung.",
    "Marienbergjoch.gpx/ArtderTour": "Rundtour",
    "Marienbergjoch.gpx/Tourenbeschreibung": "Die Strecke verl%uFFFDuft %uFFFDber das Marienbergjoch bis kurz vor den Ort Biberwier am Bike Trail Tirol. Ab der Abzweigung %uFFFDFernpass Seen%uFFFD folgt man der Radwegbeschilderung %uFFFDMieminger Gebirge Tour%uFFFD zur%uFFFDck %uFFFDber den Fernpass bis Nassereith. Beim Startpunkt f%uFFFDhrt man auf der Gemeindestra%uFFFDe in %uFFFDstlicher Richtung leicht ansteigend Richtung %uFFFDDormitz, Rossbach%uFFFD. Der Weg verl%uFFFDuft entlang des Rossbachs bis zur Abzweigung %uFFFDMarienbergjoch, 605%uFFFD. Hier zweigt man links ab und radelt weiter auf einer Asphaltstra%uFFFDe (nun etwas steiler) durch den Weiler Aschland bis zur Abzweigung zum Marienbergjoch. Hier wiederum links ab und auf dem Forstweg bis zur Marienbergalm. Der Forstweg wird nun etwas schlechter und zieht durchs Schigebiet bis zum Marienbergjoch. Auf der anderen Seite f%uFFFDhrt eine gut ausgebaute Forststra%uFFFDe (bis zur Sunnalm etwas steiler) wiederum durchs Schigebiet in einigen Serpentinen hinunter zur Abzweigung %uFFFDWeissensee, Fernpass-Seen, Seenroute (837), Nassereither Alm%uFFFD. Hier zweigt man links auf die Wiese ab (der Weg f%uFFFDhrt zun%uFFFDchst auf der Wiese entlang und ist kaum sichtbar) und radelt am Weissensee entlang. Die Route f%uFFFDhrt nun leicht ansteigend, zuerst auf einem schlechteren, sp%uFFFDter auf einem guten Forstweg bis zum h%uFFFDchsten Punkt dieses Streckenabschnitts. Hier, direkt bei der Infotafel zur %uFFFDVia Claudia Augusta%uFFFD geht es rechts Richtung Nassereith weiter. Bei Kilometer 21,7 %uFFFDberquert man vorsichtig die Fernpassbundesstra%uFFFDe und f%uFFFDhrt auf der anderen Seite weiter Richtung %uFFFDFernstein, Nassereith%uFFFD. Nach etwa 300 Metern zweigt man scharf links ab (Nassereith 610), um wiederum nach 300 Metern links abw%uFFFDrts dem Radweg %uFFFDFernstein, Nassereith%uFFFD zu folgen. Nun wird aus dem Forstweg ein Singletrail, der jedoch meist sehr gut befahrbar ist. Kurz nach dem Schloss Fernstein erreicht man eine Asphaltstra%uFFFDe und f%uFFFDhrt immer geradeaus weiter, am Campingplatz vorbei bis zu dem Punkt, an dem eine enge Unterf%uFFFDhrung unter der Fernpassbundesstra%uFFFDe durchf%uFFFDhrt. Hier geht es unten durch und man folgt der Beschilderung %uFFFDNassereith, Via Claudia Augusta%uFFFD. Zun%uFFFDchst f%uFFFDhrt man auf einem Forstweg, sp%uFFFDter erreicht man die Stra%uFFFDe, auf der man durch das Ortszentrum von Nassereith bis an den s%uFFFDdlichen Ortsrand (Ausgangspunkt) radelt.",
    "Marienbergjoch.gpx/Koordinaten Start": "47.319768, 10.830670",
    "Marienbergjoch.gpx/Start": "Nassereith",
    "Marienbergjoch.gpx/Koordinaten Ziel": "47.319768, 10.830670",
    "Marienbergjoch.gpx/Ziel": "Nassereith",
    "Marienbergjoch.gpx/auf": 1200,
    "Marienbergjoch.gpx/ab": 1200,
    "Marienbergjoch.gpx/HoechsterPunkt": 1800,
    "Marienbergjoch.gpx/Schwierigkeit": "schwer",
    "Marienbergjoch.gpx/Laenge": "29,5",
    "Marienbergjoch.gpx/Zeit": 5,
    "Marienbergjoch.gpx/Parkplatz": "",
    "Marienbergjoch.gpx/Koordinaten Parkplatz": "47.315259, 10.843393",
    "Marienbergjoch.gpx/Gebirgszug": "Mieminger Kette",
    "Marienbergjoch.gpx/Quelle": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-marienbergjoch",
    "Marienbergjoch.gpx/Einkehr": "Marienbergalm",
    "Marienbergjoch.gpx/EinkehrKoordinaten": "47.342083, 10.899485",
    "Marienbergjoch.gpx/EinkehrHomepage": "http://www.tirol.at/reisefuehrer/sport/wandern/wandertouren/a-almwanderung-marienbergalm",
    "Marienbergjoch.gpx/Einkehr1": "Gasthof Aschlandhof",
    "Marienbergjoch.gpx/Einkehr1Koordinaten": "47.315646, 10.888394",
    "Marienbergjoch.gpx/Einkehr1Homepage": "http://www.aschlandhof.com/",
    "Marienbergjoch.gpx/specials": "Wei%uFFFDensee",
    "Marienbergjoch.gpx/specialsKoordinaten": "47.362701, 10.872196",
    "Marienbergjoch.gpx/specialsWebsite": "http://www.seenradwege.com/Weissensee.htm",
    "Marienbergjoch.gpx/specials1": "Fernstein",
    "Marienbergjoch.gpx/specials1Koordinaten": "47.345703, 10.817517",
    "Marienbergjoch.gpx/specials1Website": "https://de.wikipedia.org/wiki/Burg_Fernstein",
    "Marienbergjoch.gpx/Foto": "bilder/marienbergjoch.jpg",
    "Guffertrunde.gpx/Titel": "Guffertrunde",
    "Guffertrunde.gpx/Kurztext": "Diese Route mit zwei Anstiegen und einer Abfahrt sorgt f%uFFFDr besonders viel Abwechslung. Erleben Sie einen eindrucksvollen Tag, an dem Sie mit Ihrem Bike nicht nur das 'sch%uFFFDnste Ende Tirols' erreichen, sondern entlang der Brandenberger Ache gleich an mehreren Stellen ihre F%uFFFD%uFFFDe ins klare Gebirgswasser strecken k%uFFFDnnen.",
    "Guffertrunde.gpx/ArtderTour": "Rundtour",
    "Guffertrunde.gpx/Tourenbeschreibung": "Ausgangspunkt ist das Kaiserhaus an der Brandenberger Ache. Zun%uFFFDchst f%uFFFDhrt man auf der Stra%uFFFDe entlang bis zur Abzweigung nach Steinberg am Rofan. Nun geht es rechterhand auf einer asphaltierten Zufahrtsstra%uFFFDe aufw%uFFFDrts bis zu einem Bauernhof. Die Stra%uFFFDe wird nun zu einem Forstweg und f%uFFFDhrt in einen Mischwald hinein. Immer 100 bis 200 Meter oberhalb der Steinberger Ache folgt man diesem Weg in westlicher Richtung bis nach Steinberg, wo man rechts auf die Hauptstra%uFFFDe einbiegt. Dieser folgt man Richtung Achenkirch bis man rechterhand einen gro%uFFFDen Parkplatz (K%uFFFDglboden) erreicht. Hier beginnt der Anstieg zur Gufferth%uFFFDtte. Auf einem gut ausgebauten Forstweg folgt man der Radwegmarkierung (464, 465) bis zur Gufferth%uFFFDtte. Von der H%uFFFDtte f%uFFFDhrt man etwa 300 Meter auf der gleichen Strecke zur%uFFFDck und zweigt nun links Richtung %uFFFDKaiserhaus, Erzherzog Johann Klause%uFFFD ab. Auf dem Forstweg folgt man nun immer der Radroute 465 bis man die Brandenberger Ache erreicht. Gleich nach der Br%uFFFDcke zweigt man rechts ab und f%uFFFDhrt entlang der Ache in s%uFFFDdlicher Richtung weiter Richtung Kaiserhaus. Nach einer kurzen Bergauf-Passage (die Brandenberger Ache flie%uFFFDt in diesem Bereich durch die Kaiserklamm) folgt eine kurze Abfahrt, ehe man links zum Kaiserhaus abzweigt.",
    "Guffertrunde.gpx/Koordinaten Start": "47.536660, 11.913398",
    "Guffertrunde.gpx/Start": "Kaiserhaus in Brandenberg",
    "Guffertrunde.gpx/Koordinaten Ziel": "47.536660, 11.913398",
    "Guffertrunde.gpx/Ziel": "Kaiserhaus in Brandenberg",
    "Guffertrunde.gpx/auf": 1000,
    "Guffertrunde.gpx/ab": 1000,
    "Guffertrunde.gpx/HoechsterPunkt": 1470,
    "Guffertrunde.gpx/Schwierigkeit": "mittelschwer",
    "Guffertrunde.gpx/Laenge": "40,5",
    "Guffertrunde.gpx/Zeit": "4h30min",
    "Guffertrunde.gpx/Parkplatz": "Parkm%uFFFDglichkeiten beim Kaiserhaus",
    "Guffertrunde.gpx/Koordinaten Parkplatz": "47.536660, 11.913398",
    "Guffertrunde.gpx/FIELD18": "",
    "Guffertrunde.gpx/Gebirgszug": "Brandenberger Alpen (Rofan)",
    "Guffertrunde.gpx/Quelle": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-guffertspitze",
    "Guffertrunde.gpx/Einkehr": "Kaiserhaus",
    "Guffertrunde.gpx/EinkehrKoordinaten": "47.536741, 11.913402",
    "Guffertrunde.gpx/EinkehrHomepage": "http://www.kaiserhaus.eu/index.php/oeffnungszeiten.html",
    "Guffertrunde.gpx/Einkehr1": "Gufferth%uFFFDtte",
    "Guffertrunde.gpx/Einkehr1Koordinaten": "47.581662, 11.799271",
    "Guffertrunde.gpx/Einkehr1Homepage": "http://www.gufferthuette.at/",
    "Guffertrunde.gpx/specials": "Kaiserklamm",
    "Guffertrunde.gpx/specialsKoordinaten": "47.540179, 11.916547",
    "Guffertrunde.gpx/specialsWebsite": "https://www.alpbachtal.at/de/sommer/wandern/naturerlebnisklammen/kaiserklamm",
    "Guffertrunde.gpx/specials1": "Dorfhaus Steinberg",
    "Guffertrunde.gpx/specials1Koordinaten": "47.513856, 11.801169",
    "Guffertrunde.gpx/specials1Website": "https://m.facebook.com/Dorfhaus.Steinberg/",
    "Guffertrunde.gpx/Foto": "bilder/Kaiserhaus-Guffertrunde.jpg",
    "VorderesOetztal.gpx/Titel": "Vorderes %uFFFDtztal",
    "VorderesOetztal.gpx/Kurztext": "Diese 37 Kilometer lange Eintages-Rundtour beginnt mit einer gem%uFFFDtlichen Auffahrt mit der Bergbahn in Oetz. Oben angekommen erwartet Mountainbiker auf 2.000 Meter Seeh%uFFFDhe ein toller Ausblick auf die %uFFFDtztaler Alpen und die Kalkberge der Mieminger Kette. Mit nur 500 H%uFFFDhenmeter aufw%uFFFDrts ist diese Mountainbiketour bestens f%uFFFDr Beginner geeignet. Die Abfahrt mit 1.000 H%uFFFDhenmeter f%uFFFDhrt durch alpine Landschaft bis hinunter ins Inntal.",
    "VorderesOetztal.gpx/ArtderTour": "Rundtour",
    "VorderesOetztal.gpx/Tourenbeschreibung": "Mit der Acherkogelbahn in Oetz geht es zun%uFFFDchst nach Hochoetz auf %uFFFDber 2.000 Meter H%uFFFDhe. Die Mitnahme von Mountainbikes ist erlaubt. Nach dem Ausstieg h%uFFFDlt man sich links am Forstweg Richtung Ochsengarten (Mountainbikeroute Nr. 659). Die Strecke f%uFFFDhrt zun%uFFFDchst abw%uFFFDrts durch das Schigebiet. Nach etwa 600 Metern f%uFFFDhrt man weiter geradeaus (%uFFFDAussichtspunkt Rotes-Wandl, Ochsengarten%uFFFD). Der gut ausgebaute Forstweg zieht nun in nordwestlicher Richtung abw%uFFFDrts. Bald gelangt man in den Zirben- Fichtenwald und es geht in einigen Serpentinen weiter abw%uFFFDrts. Im Tal angekommen f%uFFFDhrt man rechts, taleinw%uFFFDrts nach Wald, bis zur Abzweigung %uFFFDHaiming%uFFFD. Nun radelt man links auf der Asphaltstra%uFFFDe bis zum h%uFFFDchsten Punkt dieses Abschnitts, dem sogenannten Sattele. Auf der anderen Seite geht es in einem Zug abw%uFFFDrts bis ins Inntal. Bei Erreichen der Bundesstra%uFFFDe %uFFFDberquert man diese und f%uFFFDhrt auf der Dorfstra%uFFFDe durch Haiming, bis man beim Gasthof Traube links abzweigt.\n\nVon nun an h%uFFFDlt man sich an die Radwegweiser %uFFFD11 %uFFFDtztal Mountainbike Trail%uFFFD. Der Inn wird %uFFFDberquert und gleich danach h%uFFFDlt man sich links Richtung Schlierenzau. Zwei Mal geht es unter der Autobahn hindurch ehe man wieder links Richtung Schlierenzau bzw. %uFFFDtztal Bahnhof abzweigt. Nun f%uFFFDhrt man durch den kleinen Weiler Schlierenzau und erreicht an dessen Ortsende die Innbr%uFFFDcke. Nun wird der Fluss wiederum %uFFFDberquert, um gleich danach links Richtung %uFFFDtztal Bahnhof weiter zu radeln. In %uFFFDtztal Bahnhof h%uFFFDlt man sich unbedingt an die Radwegmarkierung %uFFFD11 %uFFFDtztal Mountainbike Trail%uFFFD. Die Route verl%uFFFDuft n%uFFFDmlich kreuz und quer durch das Dorf. Am westlichen Ortsrand f%uFFFDhrt die Strecke nun parallel zur Eisenbahn in den Wald. Ab hier folgt man immer der gr%uFFFDnen Radwegbeschilderung Richtung Roppen. Die %uFFFDtztaler Ache wird auf einer Holzbr%uFFFDcke %uFFFDberquert. Gleich dahinter liegt die Water Area 47.\n\nWeiter geht es auf dem Radweg vorbei am Weiler %uFFFDtzbruck bis nach Roppen. Auf der Dorfstra%uFFFDe f%uFFFDhrt man bis kurz unterhalb der Kirche und zweigt links zu dieser ab. Nun radelt man ansteigend durch das Dorf Richtung Sautens. Durch den %uFFFDSautener Forchet%uFFFD gelangt man nun nach Sautens. Im Ortszentrum beim %uFFFDFriseur-Bergsport- Laden%uFFFD h%uFFFDlt man sich geradeaus Richtung Oetz. Nun f%uFFFDhrt man durch Wiesen bis zur Zufahrtstra%uFFFDe zum Piburger See. Hier links ab und %uFFFDber die %uFFFDtztaler Ache, gleich nach der Br%uFFFDcke rechts ab auf den Achenweg, bereits im Dorf Oetz. Etwa 400 Meter weiter zweigt man links zur Bundesstra%uFFFDe ab. Taleinw%uFFFDrts f%uFFFDhrt man die restlichen 500 Meter auf der Bundesstra%uFFFDe bis zur Talstation der Bergbahn.",
    "VorderesOetztal.gpx/Koordinaten Start": "47.198614, 10.902923",
    "VorderesOetztal.gpx/Start": "Oetz, Talstation Acherkogelbahn",
    "VorderesOetztal.gpx/Koordinaten Ziel": "47.198614, 10.902923",
    "VorderesOetztal.gpx/Ziel": "Oetz, Talstation Acherkogelbahn",
    "VorderesOetztal.gpx/auf": 500,
    "VorderesOetztal.gpx/ab": 1700,
    "VorderesOetztal.gpx/HoechsterPunkt": 2020,
    "VorderesOetztal.gpx/Schwierigkeit": "mittelschwer",
    "VorderesOetztal.gpx/Laenge": 37,
    "VorderesOetztal.gpx/Zeit": "4h30min",
    "VorderesOetztal.gpx/Parkplatz": "Talstation der Gondelbahn in Hochoetz",
    "VorderesOetztal.gpx/Koordinaten Parkplatz": "47.198614, 10.902923",
    "VorderesOetztal.gpx/Gebirgszug": "Stubaier Alpen",
    "VorderesOetztal.gpx/Quelle": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-vorderes-oetztal",
    "VorderesOetztal.gpx/Einkehr": "Gasthof Rafting Alm",
    "VorderesOetztal.gpx/EinkehrKoordinaten": "47.259608, 10.876103",
    "VorderesOetztal.gpx/EinkehrHomepage": "https://www.raftingalm.de/",
    "VorderesOetztal.gpx/Einkehr1": "Oilers 69",
    "VorderesOetztal.gpx/Einkehr1Koordinaten": "47.241905, 10.878112",
    "VorderesOetztal.gpx/Einkehr1Homepage": "http://www.oilers69.com/",
    "VorderesOetztal.gpx/specials": "Erlebnisbad %uFFFDtz",
    "VorderesOetztal.gpx/specialsKoordinaten": "47.200440, 10.905384",
    "VorderesOetztal.gpx/specialsWebsite": "https://www.oetz.com/erlebnisbad-oetz",
    "VorderesOetztal.gpx/specials1": "Area 47",
    "VorderesOetztal.gpx/specials1Koordinaten": "47.228989, 10.844389",
    "VorderesOetztal.gpx/specials1Website": "area47.at",
    "VorderesOetztal.gpx/Foto": "bilder/sautens-oetztal.jpg"
  }