window.TOURENINFO={
  "Gaisberg_Gipfel.gpx": {
    "Titel": "Gaisberg Gipfel",
    "Kurztext": "Der Gaisberg bietet mit einer Höhe von 1287 Meter ein beliebtes Ausflugsziel für jung und alt. Als besondere Belohnung nach einem harten Aufstieg erwartet einen der Sender Gaisberg und eine atemberaubende Aussicht über Salzburg",
    "Tourenbeschreibung": "Gaisberg Gipfel ( Panorama ) : über Gänsbrunnstraße, Zistelalm, Gaisberg Landesstraße - Oberwinkl - Vorderfager",
    "KoordinatenStart": "47.766907, 13.07373",
    "Start": "Hellbrunner Brücke",
    "KoordinatenZiel": "47.803581, 13.11141",
    "Ziel": "Guggenthal bei Salzburg",
    "auf": 850,
    "ab":850,
    "HoechsterPunkt":1275,
    "NiedrigsterPunkt":421,
    "Schwierigkeit": "schwer",
    "Kondition":"5/6",
    "Technik":"5/6",
    "Landschaft":"5/6",
    "Laenge": 26,
    "Zeit": 6,
    "Parkplatz": "Park & Ride Gruberfeldstraße an der Wolfgangseestraße",
    "Quelle": "https://www.bergfex.at/sommer/salzburg/touren/mountainbike/73665,gaisberg-gipfel-panorama--ueber-gaensbrunnstrasse-zistelalm-gaisberg-landesstrasse--oberwinkl--vorderfager/",
    "Foto": "",
  },
  
  "Gaisberg_Zistelam.gpx": {
    "Titel": "Gaisberg Zistelalm",
    "Kurztext": "Diese Tour führt Sie vorbei an der malerischen Zistelalm. Dinieren Sie märchenhaft auf 1001 Metern über den Stränden des Mittelmeers. Kulinarik wird hier großgeschrieben. ",
    "Tourenbeschreibung": "MTB: Gaisberg Zistelam: Gänsbrunnstraße ( Panorama ) - Oberwinkl - Vorderfager - Glasenbach",
    "KoordinatenStart": "47.795563, 13.084428",
    "Start": "Salzburg Aigen-Abfalter",
    "KoordinatenZiel": "47.79565, 13.08432",
    "Ziel": "Salzburg Aigebn-Abfalter",
    "auf": 584,
    "ab":584,
    "HoechsterPunkt":1001,
    "NiedrigsterPunkt":431,
    "Schwierigkeit": "schwer",
    "Kondition":"5/6",
    "Technik":"5/6",
    "Landschaft":"5/6",
    "Laenge": 18.1,
    "Zeit": 5,
    "Parkplatz": "Volksschule Abfalter",
    "Quelle": "https://www.bergfex.at/sommer/salzburg/touren/mountainbike/73608,gaisberg-zistelam-ueber-gaensbrunnstrasse-panorama--oberwinkl--vorderfager/",
    "Foto": "",
  },

  "Hoeglrunde.gpx": {
    "Titel": "Hoeglrunde",
    "Kurztext": "Die Högl - Runde bietet das perfekte Fahrerlebis für jung und alt. Sie zeichnet sich durch einen mäßigen Schwierigkeitsgrad aus und bietet somit die perfekte Grundlage für einen gelungenen Familienausflug ins Grüne.",
    "Tourenbeschreibung": "Vom Ortszentrum Piding geht’s auf Asphalt aufwärts zum Berggasthof Johannishögl und der daneben liegenden Kirche. Der weitere Weg führt uns über die Neubichleralm zur Stroblalm, von der man eine herrliche Aussicht genießen kann. Jetzt geht's abwärts -  danach erfolgt ein kurzer Anstieg über Lebloh nach Steinhögl. Auf dem Radweg 'Rund um den Högl' (weißer Sendeturm im Kreis auf orangem Hintergrund) kommen wir wieder nach Piding zurück.",
    "KoordinatenStart": "47.770111, 12.91143",
    "Start": "Pidinger Hauptbahnhof",
    "KoordinatenZiel": "47.77002, 12.91151",
    "Ziel": "Ortszentrum Piding",
    "auf": 540,
    "ab":540,
    "HoechsterPunkt": 768,
    "NiedrigsterPunkt": 453,
    "Schwierigkeit": "leicht",
    "Kondition":"2/6",
    "Technik":"2/6",
    "Landschaft":"5/6",
    "Laenge": 23.87,
    "Zeit": 2.5,
    "Parkplatz": "Ortszentrum - Haus der Vereine",
    "Quelle": "https://www.bergfex.de/sommer/bayern/touren/mountainbike/10577,mtb-24--hoegl-runde-von-sueden/",
    "Foto": "",
  },

  "Kleine_Dax_Lueg_Ausfahrt.gpx": {
    "Titel": "Kleine Dax Lueg Ausfahrt",
    "Kurztext": "Entfliehen Sie in kurzer Zeit der Hektik der Stadt in das ruhig und idyllisch hoch über Salzburg gelegene Daxlueg. Erfrischen Sie ihre Lungen mit sauberer Bergluft und genießen Sie heimische Kötlichkeiten der lokalen Gastronomie. ",
    "Tourenbeschreibung": "Schöne, kleine Ausfahrt von Salzburg über Dax Lueg nach Guggental und über die Radauer Kurve wieder nach Salzburg.",
    "KoordinatenStart": "47.80685, 13.045816",
    "Start": "Salzburg - Rudolfskai",
    "KoordinatenZiel": "47.806553, 13.045541",
    "Ziel": "Salzburg - Rudolfskai",
    "auf": 886,
    "ab":590,
    "HoechsterPunkt":806,
    "NiedrigsterPunkt":463,
    "Schwierigkeit": "leicht",
    "Kondition":"4/6",
    "Technik":"1/6",
    "Landschaft":"5/6",
    "Laenge": 23.75,
    "Zeit": 1.2,
    "Parkplatz": "Parkplätze Innenstadt",
    "Quelle": "https://www.bergfex.at/sommer/salzburg/touren/mountainbike/177903,kleine-dax-lueg-ausfahrt/",
    "Foto": "",
  },

  "Muehlsteinrunde.gpx": {
    "Titel": "Mühlsteinrunde",
    "Kurztext": "Durch Wald und Wiese, über Stock und Stein, für diese Tour durch malerische Bauernhöfe in die Glasenbachklammm hinein ",
    "Tourenbeschreibung": "Eine nette kleine Runde im Nahbereich der Stadt Salzburg, die besonders als Eingewöhnungstour zu Beginn der Radsaison oder am Abend nach der Arbeit ideal ist.",
    "KoordinatenStart": "47.767231, 13.09388",
    "Start": "Parkplatz Glasenbachklamm",
    "KoordinatenZiel": "47.767288, 13.093844",
    "Ziel": "Parkplatz Glasenbachklamm",
    "auf": 750,
    "ab":750,
    "HoechsterPunkt":950,
    "NiedrigsterPunkt":468,
    "Schwierigkeit": "mittel",
    "Kondition":"3/6",
    "Technik":"2/6",
    "Landschaft":"3/6",
    "Laenge": 18.19,
    "Zeit": 2,
    "Parkplatz": "Parkplatz Glasenbachklamm",
    "Quelle": "https://www.bergfex.at/sommer/salzburg/touren/mountainbike/45864,muehlsteinrunde/",
    "Foto": "",
  },

  "Rupertiwinkel.gpx": {
    "Titel": "Rupertiwinkel",
    "Kurztext": "Der Startpunkt für diese Tour ist in Wals, Sie können diese Tour auch überall entlang der Strecke beginnen. Los geht es in Wals, sie fahren nach Grünau, über den Grünauer Steg nach Hammerau. Entlang der Saalach Flussabwärts bis nach Freilassing. Weiter am Radweg durch Freilassing Richtung Saaldorf – Surheim vorbei am Abtsdorfer See bis Laufen. Von Oberndorf aus geht es wieder Flussaufwärts bis zur Fahrradunterführung der Autobahn. Dieser überqueren Sie, und fahren über Liefering nach Taxham zum Schloss Klessheim und über Siezenheim zurück nach Wals.",
    "Tourenbeschreibung": "Von Wals über den bayrische Seite zum Abtsdorfer See weiter nach Laufen, durch Oberndorf Richtung Anthering und zurück nach Wals durch die Stadt Salzburg. ",
    "KoordinatenStart": "47.791451000, 12.945935000",
    "Start": "Hotel Königgut ",
    "KoordinatenZiel": "47.790562000, 12.958375000",
    "Ziel": "Hotel Königgut",
    "auf": 132,
    "ab":144,
    "HoechsterPunkt":468,
    "NiedrigsterPunkt":390,
    "Schwierigkeit": "mittel",
    "Kondition":"3/6",
    "Technik":"0/6",
    "Landschaft":"4/6",
    "Laenge": 48.27,
    "Zeit": 3,
    "Parkplatz": "Parkplätze Hotel Königgut",
    "Quelle": "https://www.bergfex.at/sommer/salzburg/touren/mountainbike/159626,rupertiwinkel-mountainbikerunde/",
    "Foto": "",
  },

  "Staufen_Umrundung.gpx": {
    "Titel": "Staufen Umrundung",
    "Kurztext": "Lassen Sie sich entführen in eine Welt der Seen und verträumten Almen und geießen eine rauschende Abfahrt durch den Bergblumengarten. Abgerundet wird das Erlebnis mit einem erquickenden Bad im Listsee. ",
    "Tourenbeschreibung": "Eine abwechslungsreiche Rundtour um das Staufenmassiv mit ständigen auf und ab.",
    "KoordinatenStart": "47.773663000, 12.795864000",
    "Start": "Parkpplatz Adlgass - Inzell",
    "KoordinatenZiel": "47.773884000, 12.796301000",
    "Ziel": "Parkpplatz Adlgass - Inzell",
    "auf": 1066,
    "ab":1012,
    "HoechsterPunkt":1048,
    "NiedrigsterPunkt":470,
    "Schwierigkeit": "mittel",
    "Kondition":"3/6",
    "Technik":"2/6",
    "Landschaft":"5/6",
    "Laenge": 38.91,
    "Zeit": 4.5,
    "Parkplatz": "Wanderparkpplatz Adlgass - Inzell",
    "Quelle": "https://www.bergfex.de/sommer/bayern/touren/mountainbike/115090,staufen--umrundung-in-den-chiemgauer-alpen/",
    "Foto": "",
  },

  "Wallersee_Rundfahrt.gpx": {
    "Titel": "Wallersee Rundfahrt",
    "Kurztext": "Eine weitläufige Seeenlandschaft mischt sich den Ausläufern der hochragenden Alpen zu einer Synfonie zwischen Wasser, Wald und Weide.",
    "Tourenbeschreibung": "Rundfahrt um den Wallersee; von der Stadt Salzburg aus; über Ischlerbahntrasse; wahlweise: gegen den Uhrzeigersinn oder im Uhrzeigersinn",
    "KoordinatenStart": "47.826916, 13.037338",
    "Start": "Salzburg - Itzling (Kaffee-Eis Schwaiger)",
    "KoordinatenZiel": "47.82729, 13.037424",
    "Ziel": "Salzburg - Itzling",
    "auf": 388,
    "ab":386,
    "HoechsterPunkt":581,
    "NiedrigsterPunkt":417,
    "Schwierigkeit": "mittel",
    "Kondition":"3/6",
    "Technik":"3/6",
    "Landschaft":"4/6",
    "Laenge": 48.10,
    "Zeit": 5,
    "Parkplatz": "Parkplätze Kaffee-Eis Schwaiger",
    "Quelle": "https://www.bergfex.at/sommer/salzburg/touren/mountainbike/67119,wallersee-rundfahrt-von-der-stadt-salzburg/",
    "Foto": "",
  },

  }